# Generated by Django 3.2.22 on 2023-10-27 15:23

from django.db import migrations
from django.db.models import Subquery

from richie.apps.core.helpers import get_permissions
from richie.apps.courses import defaults, models


def update_model_page_permissions(model, permissions):
    roles = models.PageRole.objects.filter(
        page__in=Subquery(model.objects.values("extended_object_id")),
        role=defaults.ADMIN,
    )
    for role in roles.iterator():
        role.group.permissions.set(get_permissions(permissions))


def update_organization_and_course_permissions(apps, schema_editor):
    new_course_permissions = [
        # Objects
        "cms.change_page",
        "cms.add_title",
        "cms.change_title",
        "cms.use_structure",
        # Filer
        "filer.add_file",
        "filer.change_file",
        "filer.view_file",
        "filer.add_image",
        "filer.change_image",
        "filer.view_image",
        "filer.can_use_directory_listing",
        "filer.change_folder",
        "filer.view_folder",
        # Plugins
        "djangocms_link.add_link",
        "djangocms_link.change_link",
        "djangocms_link.delete_link",
        "djangocms_link.view_link",
        "djangocms_picture.add_picture",
        "djangocms_picture.change_picture",
        "djangocms_picture.delete_picture",
        "djangocms_picture.view_picture",
        "djangocms_text_ckeditor.add_text",
        "djangocms_text_ckeditor.change_text",
        "djangocms_text_ckeditor.delete_text",
        "djangocms_text_ckeditor.view_text",
        "djangocms_video.add_videoplayer",
        "djangocms_video.change_videoplayer",
        "djangocms_video.delete_videoplayer",
        "djangocms_video.view_videoplayer",
        "djangocms_video.add_videosource",
        "djangocms_video.change_videosource",
        "djangocms_video.delete_videosource",
        "djangocms_video.view_videosource",
        "djangocms_video.add_videotrack",
        "djangocms_video.change_videotrack",
        "djangocms_video.delete_videotrack",
        "djangocms_video.view_videotrack",
        "plain_text.add_plaintext",
        "plain_text.change_plaintext",
        "plain_text.delete_plaintext",
        "plain_text.view_plaintext",
        "section.add_section",
        "section.change_section",
        "section.delete_section",
        "section.view_section",
        "simple_text_ckeditor.add_simpletext",
        "simple_text_ckeditor.change_simpletext",
        "simple_text_ckeditor.delete_simpletext",
        "simple_text_ckeditor.view_simpletext",
        "courses.add_personpluginmodel",
        "courses.change_personpluginmodel",
        "courses.delete_personpluginmodel",
        "courses.view_personpluginmodel",
        "courses.add_categorypluginmodel",
        "courses.change_categorypluginmodel",
        "courses.delete_categorypluginmodel",
        "courses.view_categorypluginmodel",
        "courses.add_licencepluginmodel",
        "courses.change_licencepluginmodel",
        "courses.delete_licencepluginmodel",
        "courses.view_licencepluginmodel",
        "courses.view_category",
        "courses.view_person",
        "glimpse.add_glimpse",
        "glimpse.change_glimpse",
        "glimpse.delete_glimpse",
        "glimpse.view_glimpse",
        "lti_consumer.add_lticonsumer",
        "lti_consumer.change_lticonsumer",
        "lti_consumer.delete_lticonsumer",
        "lti_consumer.view_lticonsumer",
        "nesteditem.add_nesteditem",
        "nesteditem.change_nesteditem",
        "nesteditem.delete_nesteditem",
        "nesteditem.view_nesteditem",
    ]
    new_organization_permissions = new_course_permissions + ["courses.change_course"]
    update_model_page_permissions(models.Course, new_course_permissions)
    update_model_page_permissions(models.Organization, new_organization_permissions)


class Migration(migrations.Migration):
    dependencies = [("courses", "0034_auto_20230817_1736")]

    operations = [migrations.RunPython(update_organization_and_course_permissions)]
